sudo: false

language: node_js

node_js:
  - 6.11.0

branches:
  only:
    - master
    - prod
    - stage
    - int
    - v0.3.3

install:
  - npm set progress=false
  - npm install
  - npm i -g firebase-ci@next
  - firebase-ci createConfig

script:
  - npm run lint:fix
  - npm run test
  - npm run build:prod

after_success:
  # - firebase-ci mapEnv
  - firebase-ci deploy

notifications:
  email:
    on_failure: change
    on_success: change
