sudo: false

language: node_js

node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
    - prod
    - stage
    - int
    - v0.3.3

script:
  # - npm run lint:fix
  # - npm run test
  - npm run build:prod

after_success:
  - npm i -g firebase-ci@2.0.0-alpha # install firebase-ci
  - firebase-ci deploy

notifications:
  email:
    on_failure: change
    on_success: change
